public enum MovieStatusEnum
{
    WatchingFor,
    DownloadQueued,
    Downloading,
    DownloadingPaused,
    Downloaded,
    NoVideoFilesError,
    TranscodingQueued,
    AnalysisStarted,
    Transcoding,
    TranscodingFinished,
    TranscodingError,
    Finished,
    FileInUse,
    FileNotFound,
    CouldNotCleanup,
    TranscodingIncomplete
}